export const AppTypes = {
    FormStore: "FormStore",
    ApplicationStore: "ApplicationStore",
    StartApplicationUseCase: "StartApplicationUseCase",
    ProcessChangeUseCase: "ProcessChangeUseCase",
    ProcessUseCase: "ProcessUseCase",
    GetApplicationUseCase: "GetApplicationUseCase",
    GetApplicationController: "GetApplicationController",
    ProcessController: "ProcessController",
    StartApplicationController: "StartApplicationController",
    ProcessChangeController: "ProcessChangeController",
    MojAddAnotherUseCase: "MojAddAnotherUseCase",
    MojAddAnotherController: "MojAddAnotherController",
    MojRemoveFromAddAnotherUseCase: "MojRemoveFromAddAnotherUseCase",
    MojRemoveFromAddAnotherController: "MojRemoveFromAddAnotherController",
};
